Vagrant.configure("2") do |config|

  VMCount = 1
  (1..VMCount).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "ubuntu2004"
      node.vm.hostname = "node#{i}.test.com"
      node.vm.network "private_network", ip: "10.0.0.1#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
        vb.name = "node#{i}"
      end
    end
  end
end
