---
- name: Install Docker dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: no
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip

- name: Add Docker GPG key
  apt_key:
    url: http://10.60.129.132/repository/docker-apt/gpg
    state: present

- name: Add apt repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - deb http://10.60.129.132/repository/ubuntu/ focal main restricted
    - deb http://10.60.129.132/repository/ubuntu/ focal-updates main restricted
    - deb http://10.60.129.132/repository/ubuntu/ focal universe
    - deb http://10.60.129.132/repository/ubuntu/ focal-updates universe
    - deb http://10.60.129.132/repository/ubuntu/ focal multiverse
    - deb http://10.60.129.132/repository/ubuntu/ focal-updates multiverse
    - deb http://10.60.129.132/repository/ubuntu/ focal-backports main restricted universe multiverse

- name: Install docker
  apt:
    name: docker.io
    state: present
    update_cache: no

- name: Install docker-compose
  get_url:
    url: http://10.60.129.132/repository/Raw-compress/binary/docker-compose/v1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Start docker
  service:
    name: docker
    state: started

- name: Configure daemon.json
  template:
    src: ./files/daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644

- name: Restart docker
  service:
    name: docker
    state: restarted
