---
- name: Setup network for host
  import_tasks: network.yml
  tags:
    - common
    - network

- name: Ensuring user {{ app_user }} exists
  import_tasks: user.yml
  tags:
    - common
    - user

- name: Ensuring Docker has installed on host
  import_tasks: docker.yml
  tags:
    - common
    - docker

# TODO: maybe install some useful package
# - name: Ensuring pip and python packages has installed on host
#   tags:
#     - common
#     - pip
