---
- name: Ensure useful package are installed
  package:
    name: "{{ common_packages }}"
    state: "{{ common_packages_state }}"

- name: Install Docker python modules
  ansible.builtin.pip:
    name:
      - docker==6.1.3
      - docker-compose=1.29.2
