---
- name: Create Docker group
  group:
    name: docker
    state: present

- name: Create {{ app_user }} user
  user:
    name: "{{ app_user }}"
    state: present
    shell: /bin/bash
    groups:
      - docker
    append: yes
    update_password: always
    password: "{{ app_user_password }}"