---
- name: Ensuring directory {{ etcd_workdir }} exists
  file:
    name: "{{ etcd_workdir }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    state: directory

- name: Ensuring config directories exists
  file:
    path: "{{ etcd_workdir }}/{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    state: directory
  loop:
    - configs

- name: Copying config files to config directories
  template:
    src: "{{ item.src }}"
    dest: "{{ etcd_workdir }}/{{ item.dest }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
  loop:
    - { src: etcd.env.j2, dest: etcd.env }

- name: Copying docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ etcd_workdir }}/docker-compose.yml"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Running etcd service
  community.docker.docker_compose:
    project_src: "{{ etcd_workdir }}"
    state: present

- name: Wait until the etcd cluster is healthy
  command: >
    docker exec -it etcd etcdctl endpoint health
    --endpoints=http://{{ host_addresses.internal.address }}:2379
  register: etcd_health_result
  until: "'is healthy' in etcd_health_result.stdout"
  retries: 5
  delay: 3
  changed_when: false

- name: Cluster health
  debug:
    msg: "{{ etcd_health_result.stdout }}"
