---
- name: Ensure directory exists
  file:
    name: "{{ app_base_dir }}/scripts"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    state: directory

- name: Copy script to remote host
  template:
    src: "clean.sh.j2"
    dest: "{{ app_base_dir }}/scripts/clean.sh"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Execute clean bash script
  command: sh {{ app_base_dir }}/scripts/clean.sh
  register: script_output

- name: Display script output
  debug:
    var: script_output.stdout_lines

- name: Clean directory
  command: rm -rf {{ app_base_dir }}/{{ clean_app_name }}
  when: clean_app_name is defined
