---
# Postgres-patroni configs
postgres_workdir: "{{ app_base_dir }}/postgres"
postgres_datadir: "{{ postgres_workdir }}/postgres-data"
postgres_datadir_container: "{{ postgres_workdir }}/postgres-data/"
postgres_image: nguyenhiep201/postgres-13.6-patroni-3.1.0:1.0.0
postgres_port: 8432
postgres_patroni_port: 8000
postgres_dbname: "postgres"
postgres_users:
  superuser:
    username: "postgres"
    password: "xxxxxx"
  replication:
    username: "replicator"
    password: "xxxxxx"
  rewind:
    username: "rewind_user"
    password: "xxxxxx"
postgres_network: 10.0.0.0/26
postgres_scope: postgres
postgres_patroni_restapi_port: 8000
