---
# Region 1 configurations
region_nodes:
  - region2node1
  - region2node2
  - region2node3
consul_datacenter: dc2
standby_cluster:
  primary_host_address: master.postgres.service.dc1.consul
  primary_port: 8432
